name: RestoPro Full Build

on:
  push:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

#################################################
# FRONTEND NEXT BUILD
#################################################
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build

#################################################
# WINDOWS EXE TAURI
#################################################
  windows:
    name: Build Windows EXE
    runs-on: windows-latest
    needs: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: dtolnay/rust-toolchain@stable

      - run: npm ci
      - run: npm run build

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#################################################
# ANDROID APK TAURI
#################################################
  android-tauri:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - run: npm ci
      - run: npm run build

      - run: npx tauri android init || true
      - run: npx tauri android build

#################################################
# FIN
#################################################
  release-files:
    name: Finish Build
    runs-on: ubuntu-latest
    needs: [windows, android-tauri]

    steps:
      - run: echo "Build terminé"